// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class them_user_va_bang_lien_quan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_user_va_bang_lien_quan));
        
        string IMigrationMetadata.Id
        {
            get { return "201807080111516_them_user_va_bang_lien_quan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
