// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class them_truong_trong_country : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(them_truong_trong_country));
        
        string IMigrationMetadata.Id
        {
            get { return "201807041730035_them_truong_trong_country"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
